### ISSUE TITLE
Minumet/Inventarios de artículos 

### ISSUE THREAD

**Issue by paolapinero** [loyos/herraven#10]
-   Usar la misma categorización por Líneas y categorías solicitada en el Master artículos de minumet.

**Comment by paolapinero** [comment]
Tony te aviso cuando estos cambios esten en el servidor

**Comment by ghost** [comment]
@paolapinero Esto es importante, avísame si necesitas ayuda en determinar los detalles

**Comment by paolapinero** [comment]
No entiendo esto, el ticket de minumet/master articulos dice:

Poder crear y asociar líneas y categorías para los artículos creados aquí
Editar y eliminar van dentro de la vista
Incluir una pequeña foto expandible siguiendo como ejemplo el pedido hecho en master de artículos de Artículos

pero no veo la relacion con el inventarios de minumet, seguro que es ese modulo de inventario? me podrias explicar cada punto mejor

**Comment by ghost** [comment]
@paolapinero en el doc. word original dice "Minumet/Master Artículos" todo lo que está aquí es para el master artículos de minutería auxiliar.

Tal como en "Artículos/Master Artículos" aquí necesito 1. categorización por lineas y categorías, visto que resultaron ser muchos artículos de naturaleza distinta (puedes entrar y ver). 2. Pasar las acciones "editar y eliminar" dentro de la vista particular de cada artículo y 3. incluir la imagen expandible tal cual como se hizo en "Artículos/Master artículos"

Hazme saber si se entiende ahora

**Comment by paolapinero** [comment]
Ah ya entendi ya entendi, entonces en tablas se van a tener que crear las categorias y subcategorias, porque este tipo de articulos no los tenian, y al momento de crearlos entonces se tienen q asociar a una subcategoria.

Esto si esta un poco larguito, de aqui al fin termino todos los tickets que tengo asignados, los dias de semana no programo mucho porque estoy super full en el trabajo, aqui soy una esclava

**Comment by paolapinero** [comment]
Listo, para ser corregido el lunes 7 despues de mediodia que lo monte al servidor

**Comment by ghost** [comment]
Hola @paolapinero cuando comentes mencioname para que me lleguen los correos y te pueda responder rápido : D

Ya voy a chequear esto

**Comment by ghost** [comment]
@paolapinero tanto lineas como categorias Minumet les falta algo, ver imagen: 

![1](https://cloud.githubusercontent.com/assets/5000398/11708157/6cf4bc32-9ede-11e5-83b5-402e3ff2faa1.png)

**Comment by paolapinero** [comment]
Ya @HerravenCardinale
