### ISSUE TITLE
personal

### ISSUE THREAD

**Issue by paolapinero** [loyos/herraven#11]
Cuando creas un miembro del personal se crea en master usuarios una especie de usuario. Y cuando lo borro en cambio, en personal se borra la info del nombre y apellido. 
La cosa es que cuando creas un miembro del personal no tiene que tocar a los usuarios del sistema. Cuando creo un usuario nuevo del sistema, la pantalla se queda en blanco y me arroja error en vez de darme acuse de recibo y mandarme de nuevo a la lista de usuarios creados. Favor borrar a dos miembros del personal retirados de la base de datos, visto que fueron de prueba.

**Comment by paolapinero** [comment]
El error de que se queda en blanco cuando creas un usuario no lo veo, sera en algun caso en especifico??

**Comment by ghost** [comment]
Traté de entrar en personal para ver esto pero me dio error fatal, ver el issue #25

**Comment by paolapinero** [comment]
Ya no da el error fatal, deberia funcionar
