### ISSUE TITLE
Clientes/Master clientes

### ISSUE THREAD

**Issue by paolapinero** [loyos/herraven#14]
-   Editar va dentro de la vista 
-   Incluir un buscador 
-   Eliminar columna de “lista de precios” y dejar solo las que están

**Comment by paolapinero** [comment]
Que significa que editar va dentro de la vista?

**Comment by ghost** [comment]
@paolapinero significa que el botón editar lo vas a conseguir dentro de la vista que tienes cuando le das clic a "Ver" y no en la lista 

![3](https://cloud.githubusercontent.com/assets/5000398/11356717/9577c388-9232-11e5-9929-3b0b08660b20.png)
