### ISSUE TITLE
Artículos/Listas de precios 

### ISSUE THREAD

**Issue by paolapinero** [loyos/herraven#17]
-   Eliminar y editar van dentro de la vista 
-   Los artículos ocultos no deben aparecer en las listas de precios
-   Al ver la lista de precios: arreglar un poco la vista del encabezado que esta descuadrada
-   Las líneas no son link, solo las categorías de artículos 
-   Arreglar un poco el pdf que arroja las listas de precio porque salen torcidos

**Comment by paolapinero** [comment]
Para ser revisado el 20/11 despues de mediodia

**Comment by ghost** [comment]
Hola @paolapinero 

Perfecto con todo, solo falta esto: 

Eliminar y editar van dentro de la vista

![2](https://cloud.githubusercontent.com/assets/5000398/11356659/f605982a-9231-11e5-831c-eb947b63d7d0.png)
