### ISSUE TITLE
Artículos/Egresos de inventarios

### ISSUE THREAD

**Issue by paolapinero** [loyos/herraven#18]
-   Correr elementos de búsqueda hacia la derecha para que se arregle encabezado.

**Comment by paolapinero** [comment]
PAra ser revisado el 20/11 en la noche

**Comment by paolapinero** [comment]
Donde queda eso que no lo veo?

**Comment by paolapinero** [comment]
ah es en almacen, pero yo veo el buscador a la derecha porfa pasame los screen de pantalla para ver como lo ves tu

**Comment by ghost** [comment]
Ahora se ve bien
