### ISSUE TITLE
candadito

### ISSUE THREAD

**Issue by paolapinero** [loyos/herraven#24]
Colocar el candadito de la pagina

**Comment by ghost** [comment]
El candadito lo va a poner Matias, en caso de que él necesite asistencia de ustedes les haré saber.

**Comment by ghost** [comment]
Matias Rosado (quien lleva el hosting y el dominio de Herraven) y a quien le pedí que implementara el candadito para Herraven me pidió que se pongan en contacto con él para consultarle unas cosas antes de hacer eso. su correo es: mathiasalberto@gmail.com y su Whatsapp es +584166967026

@loyos @paolapinero
