### ISSUE TITLE
Fundición/Ordenes de producción 

### ISSUE THREAD

**Issue by paolapinero** [loyos/herraven#8]
-   Cuando haces clic en una nueva de producción deberías primero escoger el molde y luego individualmente haces la orden. Lo que ocurre es que el navegador me obliga a llenar todas las
  Casillas “obligatorias” de todos los moldes y no puedo crear la orden.
-   Aparentemente el filtro de moldes para una nueva orden de producción no esta funcionando

**Comment by paolapinero** [comment]
Tony no entiendo el punto 1, el solo valida el numero de inyecciones del cuadro donde le das pedir, lo probe y me funciona, explicame bien porfa, con respecto al filtro ya lo acomode

**Comment by ghost** [comment]
Tienes razón, no es en fundición, son las ordenes de producción de Minumet. Ver imagen 
![2](https://cloud.githubusercontent.com/assets/5000398/10988718/3553762a-8411-11e5-931a-fd1f40cb4668.png)
